//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChallengePatricio.Recursos {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TraduccionIngles {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TraduccionIngles() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ChallengePatricio.Recursos.TraduccionIngles", typeof(TraduccionIngles).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The amount of figures is.
        /// </summary>
        internal static string CantidadFiguras {
            get {
                return ResourceManager.GetString("CantidadFiguras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circle.
        /// </summary>
        internal static string Circulo {
            get {
                return ResourceManager.GetString("Circulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount of Circles in the list.
        /// </summary>
        internal static string CirculosEnLista {
            get {
                return ResourceManager.GetString("CirculosEnLista", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Square.
        /// </summary>
        internal static string Cuadrado {
            get {
                return ResourceManager.GetString("Cuadrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount of Squares in the list.
        /// </summary>
        internal static string CuadradosEnLista {
            get {
                return ResourceManager.GetString("CuadradosEnLista", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THANK YOU, COME BACK SOON !!!.
        /// </summary>
        internal static string Despedida {
            get {
                return ResourceManager.GetString("Despedida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to the figures app, please choose an option to view.
        /// </summary>
        internal static string MensajeBienvenida {
            get {
                return ResourceManager.GetString("MensajeBienvenida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1- Square / 2- Circle / 3- Equilateral Triangle / 4- Rectangular Trapezoid / 5- Total Figures / 6- EXIT.
        /// </summary>
        internal static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is not the correct option, try again.
        /// </summary>
        internal static string OpcionIncorrecta {
            get {
                return ResourceManager.GetString("OpcionIncorrecta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perimeter.
        /// </summary>
        internal static string Perimetro {
            get {
                return ResourceManager.GetString("Perimetro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rectangular Trapezoid.
        /// </summary>
        internal static string TrapecioRectangulo {
            get {
                return ResourceManager.GetString("TrapecioRectangulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount of Rectangular Trapezoid in the list.
        /// </summary>
        internal static string TrapeciosRectEnLista {
            get {
                return ResourceManager.GetString("TrapeciosRectEnLista", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equilateral Triangle.
        /// </summary>
        internal static string TrianguloEquilatero {
            get {
                return ResourceManager.GetString("TrianguloEquilatero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount of Equilaterals Triangles in the list.
        /// </summary>
        internal static string TriangulosEnLista {
            get {
                return ResourceManager.GetString("TriangulosEnLista", resourceCulture);
            }
        }
    }
}
