//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChallengePatricio.Recursos {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TraduccionPortugues {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TraduccionPortugues() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ChallengePatricio.Recursos.TraduccionPortugues", typeof(TraduccionPortugues).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantidad e Figuras.
        /// </summary>
        internal static string CantidadFiguras {
            get {
                return ResourceManager.GetString("CantidadFiguras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Círculo.
        /// </summary>
        internal static string Circulo {
            get {
                return ResourceManager.GetString("Circulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circles na Lista.
        /// </summary>
        internal static string CirculosEnLista {
            get {
                return ResourceManager.GetString("CirculosEnLista", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quadrado.
        /// </summary>
        internal static string Cuadrado {
            get {
                return ResourceManager.GetString("Cuadrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Squares na Lista.
        /// </summary>
        internal static string CuadradosEnLista {
            get {
                return ResourceManager.GetString("CuadradosEnLista", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Até a próxima.
        /// </summary>
        internal static string Despedida {
            get {
                return ResourceManager.GetString("Despedida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bem-vindo ao aplicativo de figuras, escolha uma opção para visualizar.
        /// </summary>
        internal static string MensajeBienvenida {
            get {
                return ResourceManager.GetString("MensajeBienvenida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1- Quadrado / 2- Círculo / 3- Triângulo Equilátero / 4- Trapézio Retangular / 5- Números Totais / 6- SAIR.
        /// </summary>
        internal static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não é a opção correta, tente novamente.
        /// </summary>
        internal static string OpcionIncorrecta {
            get {
                return ResourceManager.GetString("OpcionIncorrecta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perímetro.
        /// </summary>
        internal static string Perimetro {
            get {
                return ResourceManager.GetString("Perimetro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trapézio Retangular.
        /// </summary>
        internal static string TrapecioRectangulo {
            get {
                return ResourceManager.GetString("TrapecioRectangulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trapézio Retangular na Lista.
        /// </summary>
        internal static string TrapecioRectEnLista {
            get {
                return ResourceManager.GetString("TrapecioRectEnLista", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Triângulo equilátero.
        /// </summary>
        internal static string TrianguloEquilatero {
            get {
                return ResourceManager.GetString("TrianguloEquilatero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Triângulos na lista.
        /// </summary>
        internal static string TriangulosEnLista {
            get {
                return ResourceManager.GetString("TriangulosEnLista", resourceCulture);
            }
        }
    }
}
